flask/website/views/home.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    request,
    url_for
)
from flask_mobility.decorators import mobile_template
from flask_login import login_required, current_user
from ..models import ORM
from ..utils import Utils

mod = Blueprint('home', __name__)


@mod.route('/home/', methods=['GET', 'POST'])
@mobile_template('{mobile/User/}home.html')
@login_required
def home(template):
    ip_address = request.remote_addr
    ORM.log_ip(ip_address)
    devices = ORM.get_devices_by_username(current_user.username_user)
    selected_device = current_user.selected_device
    return render_template(
        template,
        devices = devices,
        selected_device=selected_device
        )


@mod.route('/localisation/', methods=['GET', 'POST'])
@login_required
def localisation():
    return render_template(
        "mobile/User/localisation.html"
        )

flask/website/views/login.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    request,
    url_for,
    current_app
)
from flask_mobility.decorators import mobile_template

from wtforms import (
    StringField,
    PasswordField,
    HiddenField
)
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm
from flask_mobility.decorators import mobile_template
from flask_login import login_required, login_user, logout_user, current_user
from ..models import ORM
from hashlib import sha256
from flask.helpers import flash

mod = Blueprint('login', __name__)


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    next = HiddenField()

    def get_data(self):
        return self.username.data

    def get_authenticated_user(self):
        user = ORM.load_user(self.username.data)
        if user is None:
            return None
        m = sha256()
        m.update(self.password.data.encode())
        passwd = m.hexdigest()
        return user if passwd == user.password_user else None


@mod.route('/login/', methods=['GET', 'POST'])
@mobile_template("{mobile/Authentification/}login.html")
def login(template):
    f = LoginForm()
    if not f.is_submitted():
        f.next.data = request.args.get("next")
    elif f.validate_on_submit():
        user = f.get_authenticated_user()
        if user:
            if not ORM.is_blocked_account_user(user.username_user):
                login_user(user)
                if user.is_admin_user:
                    next = f.next.data or url_for("admin.admin_home")
                else:
                    next = f.next.data or url_for("home.home")
                return redirect(next)
            else:
                flash("Your account has been blocked. Please contact us if it is an error.","error")
                return redirect(url_for("login.login"))
        else:
            flash("Incorrect logins.","error")
    return render_template(
        template,
        form=f,
    )

flask/website/views/settings.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    send_from_directory,
    url_for,
    request
)
from flask_mobility.decorators import mobile_template
from ..models import ORM
from ..utils import Utils
from flask_login import current_user
from werkzeug.utils import secure_filename
from ..app import app
import os
import imghdr
import hashlib
from random import randint
from flask_login import current_user, login_required
from hashlib import sha256
from flask.helpers import flash

mod = Blueprint('settings', __name__)


@mod.route('/settings/', methods=['GET'])
@mobile_template("{mobile/Settings/}settings.html")
@login_required
def settings(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(
        template,
        devices=devices
    )


"""
ACCOUNT
"""


@mod.route('/settings/account/', methods=['GET'])
@mobile_template("{mobile/Settings/}account.html")
@login_required
def settings_account(template):
    files = os.listdir(app.config['UPLOAD_PATH'])
    devices = ORM.get_devices_by_username(current_user.username_user)
    subscription_name = ORM.get_subscription_name_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        files=files,
        subscription_name=subscription_name,
    )


@mod.route('/settings/account/update/', methods=['POST'])
@login_required
def settings_account_update():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    mail = result['email']
    mdp = result['password']
    code = result['postal-code']
    ville = result['town']
    rue = result['street']

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)
    if confirmpassword == password:
        validation, message = Utils.is_valid_change_account(mdp, tel, mail, ville, rue, code)
        if validation:
            ORM.update_user(mdp, tel, first, last, mail, ville, code, rue)
            flash(message, "success")
            return redirect(url_for('settings.settings_account'))

        flash(message, "error")
        return redirect(url_for('settings.settings_account'))

    flash("Incorrect Password. Changes were not applied!", "error")
    return redirect(url_for("settings.settings_account"))


'''
DEVICES
'''


@mod.route('/settings/device/', methods=['GET'])
@mobile_template("{mobile/Settings/}device.html")
@login_required
def settings_devices(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    selected = ORM.get_current_name_device_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        selected_device=selected
    )


@mod.route('/settings/devices/update/', methods=['GET', 'POST'])
@login_required
def settings_devices_update():
    name = request.form.get("name")
    movement = request.form.get("movement")
    delay = request.form.get("delay")

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)
    if confirmpassword == password:
        ORM.update_device_parameters(current_user.username_user, name)
        flash("Changes have been applied!", "success")
        return redirect(url_for("settings.settings_devices"))
    flash("Incorrect Password. Changes were not applied.", "error")
    return redirect(url_for("settings.settings_devices"))


'''
CONTACT
'''


@mod.route('/settings/contacts/', methods=['GET'])
@mobile_template("{mobile/Settings/}contacts.html")
@login_required
def settings_contact(template):
    contacts = ORM.get_contacts_by_user(current_user.username_user)
    devices = ORM.get_devices_by_username(current_user.username_user)
    number_contacts = ORM.get_number_of_contacts_by_username(current_user.username_user)

    return render_template(
        template,
        contacts=contacts,
        devices=devices,
        number=number_contacts
    )


@mod.route('/settings/contacts/update/', methods=['GET', 'POST'])
@mobile_template("{mobile/Settings/}update_contact.html")
@login_required
def settings_contact_update(template):
    result = request.form
    id_contact = result["id-contact"]
    action = result["action"]
    if action == "edit":
        contact = ORM.get_contact_by_id(id_contact)
        first = contact.firstname_contact
        last = contact.lastname_contact
        tel = contact.num_contact
        devices = ORM.get_devices_by_username(current_user.username_user)
        return render_template(template, id_contact=id_contact, first=first, last=last, tel=tel,
                               devices=devices)

    ORM.remove_contact(id_contact)
    return redirect(url_for('settings.settings_contact'))


@mod.route('/settings/contacts/update/check/', methods=['GET', 'POST'])
@login_required
def settings_contact_update_check():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    id_contact = result['id-contact']

    if first != "" and last !="":
        if Utils.is_valid_tel(tel):
            ORM.update_contact(tel, first, last, id_contact)
            flash("Contact has been updated.", "success")
        else:
            flash("Invalid phone number. Update failed.","error")
    else:
        flash("First name and Last name should not be empty. Update failed.","error")
    return redirect(url_for("settings.settings_contact"))


@mod.route('/settings/contacts/add/', methods=['GET'])
@mobile_template('{mobile/Settings/}add_contact.html')
@login_required
def settings_contact_add(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(template, devices=devices)


@mod.route('/settings/contacts/add/check/', methods=['GET', 'POST'])
@login_required
def settings_contact_add_check():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    device = ORM.get_current_num_device_by_username(current_user.username_user)
    img = '/static/pc/assets/avatar.png'

    if first != "" and last !="":
        if Utils.is_valid_tel(tel):
            ORM.new_contact(tel, first, last, img, device)
            flash("Contact has been added.", "success")
        else:
            flash("Invalid phone number.","error")
    else:
        flash("First name and Last name should not be empty.","error")
    return redirect(url_for("settings.settings_contact"))


'''
CREDIT CARD MOBILE
'''


@mod.route('/settings/card/', methods=['GET'])
@mobile_template("{mobile/Settings/}credit-card.html")
@login_required
def settings_card(template):
    return render_template(template)


'''
PAYMENT
'''


@mod.route('/settings/payment/', methods=['GET'])
@mobile_template("{mobile/Settings/}payment.html")
@login_required
def settings_payment(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(template, devices=devices)


@mod.route('/settings/payment/edit/', methods=['GET', 'POST'])
@mobile_template("{mobile/Settings/}edit_payment.html")
@login_required
def settings_payment_edit(template):
    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        devices = ORM.get_devices_by_username(current_user.username_user)
        return render_template(template, devices=devices)

    flash("Incorrect Password.", "error")
    return redirect(url_for("settings.settings_payment"))


@mod.route('/settings/payment/edit/check/', methods=['GET', 'POST'])
@login_required
def settings_payment_edit_check():
    number = request.form.get("number")
    holder_name = request.form.get("holder")
    expiration = request.form.get("expiration")
    cvv = request.form.get("cvv")

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        flash("Payment service is not available for the moment. Changes were not applies.", "error")
        return redirect(url_for('settings.settings_payment'))

    flash("Payment service is not available for the moment. Changes were not applies.", "error")
    return redirect(url_for('settings.settings_payment'))


@mod.route('/settings/subscription/', methods=['GET'])
@mobile_template("{mobile/Settings/}subscription.html")
@login_required
def settings_subscriptions(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    subscriptions = ORM.get_subscriptions()
    features = Utils.str_collon_to_list(ORM.get_subscriptions_features()[0])
    subscription_name = ORM.get_subscription_name_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        subscriptions=subscriptions,
        features=features,
        subscription_name=subscription_name
    )


@mod.route('/settings/subscription/update/', methods=['POST'])
@login_required
def settings_subscriptions_update():
    sub = request.form.get('sub')

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        if sub == "cancel":
            ORM.remove_device(current_user.selected_device)
            if not len(ORM.get_devices_by_username(current_user.username_user)):
                current_user.selected_device = None
                ORM.block_user(current_user.username_user)
            else:
                current_user.selected_device = ORM.get_devices_by_username(current_user.username_user)[0]

flask/website/views/support.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    url_for,
    request,
    Response
)
from ..app import db
from ..models import ORM, TICKET, USER, MESSAGE
from flask_mobility.decorators import mobile_template
from flask_login import login_required, current_user

mod = Blueprint('support', __name__)

@login_required
@mod.route('/support/', methods=['GET'])
@mobile_template('{mobile/User/}support.html')
def support(template):
    messages = {}

    if not current_user.is_admin_user:
        open_tickets_user = ORM.get_open_ticket_user(current_user.username_user)

        if len(open_tickets_user) != 0:
            for ticket in open_tickets_user:
                messages[ticket.id_ticket] = ORM.get_message_by_ticket_id(ticket.id_ticket)
    else:
        open_tickets = ORM.get_open_ticket()
        for ticket in open_tickets:
            messages[ticket.id_ticket] = ORM.get_message_by_ticket_id(ticket.id_ticket)
    
    last_messages = {}
    for i_mes in messages.keys():
        last_messages[i_mes] = ORM.get_last_message_by_ticket_id(i_mes)
    
    return render_template(
        template,
        messages = messages,
        picture = ORM.get_picture_message_from_username(current_user.username_user),
        last_messages= last_messages,
        devices = ORM.get_devices_by_username(current_user.username_user)
    )

@login_required
@mod.route('/support/<int:id_ticket>/', methods=['GET'])
def support_message(id_ticket):
    return render_template(
        'mobile/User/support-bis.html',
        id_ticket = id_ticket,
        messages = ORM.get_message_by_ticket_id(id_ticket),
        picture = ORM.get_picture_message_from_username(current_user.username_user),
        )

@login_required
@mod.route('/support/message/new', methods=['POST'])
def support_message_new():
    if request.method == 'POST':
        contenu_message = request.json['content']
        is_admin = request.json['is_admin']
        date = request.json['date']
        id_ticket = request.json['id_ticket']
        username = request.json['username']

        msg = MESSAGE(is_admin, date, contenu_message, id_ticket, username)
        db.session.add(msg)
        db.session.commit()

        return Response(status=200)

@login_required
@mod.route('/support/ticket/new', methods=['POST'])
def support_new_ticket():
    title = request.form.get('ticket')
    if not current_user.is_authenticated:
        return redirect(url_for('login'))
    user = current_user.username_user
    ticket = TICKET(title,0,user)
    db.session.add(ticket)
    db.session.commit()
    return redirect(url_for('support.support'))


@login_required
@mod.route('/support/ticket/close', methods=['POST'])
def support_delete_ticket():
    id_ticket = request.form.get('id_ticket')
    ORM.remove_tickets_by_id(id_ticket)
    return redirect(url_for('support.support'))


@login_required
@mod.route('/support/ticket/close/<int:id_ticket>', methods=['POST'])
def support_delete_ticket_by_id(id_ticket):
    ORM.remove_tickets_by_id(id_ticket)
    return redirect(url_for('support.support'))


@login_required
@mod.route('/support/<int:user_id>/tickets/all', methods=['GET'])
def get_user_tickets_by_id(user_id):
    res = "<ul>"
    list_ticket = ORM.get_user_tickets(user_id)
    for ticket in list_ticket:
        res += f"<li><p>ID ticket: {ticket.id_ticket}</p>" \
               f"<p>Title ticket: {ticket.title_ticket}" \
               f"<p>Is closed?: {ticket.is_closed_ticket}</p></li>"
    res += "</ul>"
    return res

@login_required
@mod.route('/support/tickets/open/all', methods=['GET'])
def get_open_tickets():
    res = "<ul>"
    open_tickets = ORM.get_open_ticket()
    for ticket in open_tickets:
        res += f"<li><p>ID ticket: {ticket.id_ticket}</p>" \
               f"<p>Title ticket: {ticket.title_ticket}" \
               f"<p>Is closed?: {ticket.is_closed_ticket}</p></li>"
    res += "</ul>"
    return res

flask/website/templates/add_contact.html
{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pc/css/add_contact.css') }}">
{% endblock style %}

{% block main %}
<div class="flex">
    <section>
        <div class="flash">
            {% include "messages.html" %}
        </div>
        <h1>Add contact</h1>
        <form action="{{ url_for('settings.settings_contact_add_check') }}" method='POST'>
            <div class="form-group1">
                <div class="form-avatar">
                    <div class="img-avatar">
                        <img id='avatar' src="{{ url_for('static', filename='pc/assets/avatar.png') }}" alt="your avatar">
                        <input id='fileinput' type="file" name="avatar">
                        <p id='picture'>Select image</p>
                    </div>
                </div>
            </div>

            <div class="form-group2">
                <div class="form-first-name">
                    <fieldset>
                        <legend>First Name</legend>
                        <input type="text" name="first-name" required>
                    </fieldset>
                </div>
                <div class="form-last-name">
                    <fieldset>
                        <legend>Last Name</legend>
                        <input type="text" name="last-name" required>
                    </fieldset>
                </div>
                <div class="form-phone">
                    <fieldset>
                        <legend>Phone Number</legend>
                        <input type="tel" name="phone" required>
                    </fieldset>
                </div>
            </div>

            <div class="form-submit">
                <a class='rotate-rouge' href="{{ request.referrer }}">Cancel</a>
                <button class='rotate-vert' type="submit">Add</button>
            </div>
        </form>
    </section>
</div>
{% endblock main %}

{% block script %}
    <script>
        $(function() {
        $('#picture').on('click', function() {
            $('#fileinput').trigger('click');
        });
        });

        $(function(){
            $('#fileinput').change(function(){
            var input = this;
            var url = $(this).val();
            var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
            if (input.files && input.files[0]&& (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg")) {
                var reader = new FileReader();
            
                reader.onload = function (e) {
                    $('#avatar').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
                
            });
            
            });
    </script>
{% endblock script %}

flask/website/templates/admin_platform.html
{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pc/css/admin_platform.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.css">
{% endblock style %}

{% block main %}
<div class="flex">
    <h2>Server Overview</h2>

    <canvas id="cpu"></canvas>
    <canvas id="ram"></canvas>
</div>
{% endblock main %}

{% block script %}

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.bundle.min.js"></script>
<script src="{{ url_for('static', filename='pc/js/admin_platform_common.js') }}"></script>
<script src="{{ url_for('static', filename='pc/js/admin_platform_cpu.js') }}"></script>
<script src="{{ url_for('static', filename='pc/js/admin_platform_ram.js') }}"></script>
<script src="{{ url_for('static', filename='pc/js/admin_platform_run.js') }}"></script>

{% endblock script %}

flask/website/templates/contacts.html
{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pc/css/contacts.css') }}">
    
{% endblock style %}

{% block main %}
<div class="flex">
    <section>
        <div class="flash">
            {% include "messages.html" %}
        </div>
        <h3><i class="fa fa-bell"></i> Contacts to Call</h3>
        {% for contact in contacts %}
        <div class="contact">
            <form action="{{ url_for('settings.settings_contact_update') }}" id="update-contact" method='POST'>
                <div class="info">
                    <img src="{{ url_for('static', filename='pc/assets/avatar.png') }}" alt="your contact avatar">
                    <h4>{{contact.firstname_contact}} {{contact.lastname_contact}}</h4>
                </div>
                
                <input type="hidden" name="id-contact" value='{{contact.id_contact}}'>
               
                <div class="action">
                    <button type="submit" name="action" value="edit">Edit</button>
                    <button type="submit" name="action" value="remove">Remove</button>
                </div>
            </form>
        </div>
        {% endfor %}
    </section>

    {% if number < 5 %}
    <a href="{{ url_for('settings.settings_contact_add') }}"><i class="fa fa-plus"></i></a>
    {% endif %}
</div>
{% endblock main %}

{% block script %}
{% endblock script %}

flask/website/templates/device.html
{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pc/css/device.css') }}">
{% endblock style %}

{% block main %}
<div class="flex">
    <section>
        <div class="flash">
            {% include "messages.html" %}
        </div>
        <h1>Your Device ({{selected_device}})</h1>
        <form action="{{ url_for('settings.settings_devices_update') }}" id="form-devices" method='POST'>
            <h3>Parameters</h3>
            <div class="slidecontainer group1">
                <label for="movement">
                    Minimum Movement Distance : <span id="value-movement"></span>m
                </label>
                <div>
                    <span>5m</span>
                    <input type="range" min="5" max="50" value="27" class="slider" name="movement" id="movement">
                    <span>50m</span>
                </div>
                
            </div>
            <div class="slidecontainer group2">
                <label for="delay">
                    SMS Sending Delay : <span id="value-delay"></span>s
                </label>
                <div>
                    <span>20s</span>
                    <input type="range" min="20" max="120" value="70" class="slider" name="delay" id="delay">
                    <span>120s</span>
                </div>
            </div>
            <div class="group3">
                <label for="name">
                    Device name :
                </label>
                <input type="text" name="name" value='{{selected_device}}'>
            </div>
            <div class="form-submit">
                <!-- My Buttons -->
                <a class='rotate-rouge' href="{{ url_for('settings.settings') }}">Cancel</a>
                <button class='rotate-vert' type="button" data-toggle="modal" data-target="#modalCenterDevice">Update</button>
            </div>
        </form>
    </section>
    <!-- Bootstrap -->
    <div class="modal fade" id="modalCenterDevice" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitleDevice" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLongTitleDevice">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Enter your password to confirm changes.</p>
                    <fieldset>
                        <input type="password" form="form-devices" name="confirmpassword" placeholder='********'>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" form="form-devices" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

{% block script %}
<script>
    var slider = document.getElementById("movement");
    var output = document.getElementById("value-movement");
    output.innerHTML = slider.value; // Display the default slider value

    // Update the current slider value (each time you drag the slider handle)
    slider.oninput = function() {
        output.innerHTML = this.value;
    }

    var slider2 = document.getElementById("delay");
    var output2 = document.getElementById("value-delay");
    output2.innerHTML = slider2.value; // Display the default slider value

    // Update the current slider value (each time you drag the slider handle)
    slider2.oninput = function() {
        output2.innerHTML = this.value;
    }
</script>
{% endblock script %}

flask/website/templates/support.html
{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pc/css/support.css') }}">
{% endblock style %}

{% block main %}
    <div class='flex'>
        <section class='tickets'>
            <div>
                <h3>Tickets</h3>
                <form id="deleteTicketForm" action="{{ url_for('support.support_delete_ticket') }}" method="POST">
                    <ul class="nav">
                        {% for numero in messages.keys() %}
                            <li onclick="activeLink(this)" class="inactive" >
                                
                                <a class="check-ticket" onclick="checkRadioButton(this)" href="#" data-toggle="modal" data-target="#deleteTicket">
                                    <i class="fa fa-check-circle"></i>
                                </a>
                                <input type="radio" name="id_ticket" value="{{numero}}">
                                
                                <a href="#tab{{ numero }}" class="a-tickets" data-toggle="tab">
                                    Ticket#{{ numero }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </form>
                {% if not current_user.is_admin_user %}
                    <a href="#" data-toggle="modal" data-target="#modalCenter">Contact BiKeeper Team</a>
                {% endif %}
            </div>
        </section>

        <section class='chat'>
            <div class="tab-content">

                {% for numero,message in messages.items() %}
                    <div id="tab{{ numero }}" role="tabpanel" class="tab-pane fade in">
                        <ul id="ul-{{numero}}">

                        </ul>
                    </div>
                {% endfor %}

            </div>
            <div class="message-input">
                <div class="wrap">
                    <input type="text" id='msg' name='msg' placeholder="Write your message..."/>
                    <button class="submit" id='send-msg'><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                </div>
            </div>
        </section>
    </div>

    <div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ url_for('support.support_new_ticket') }}" method='POST'>
                    <div class="modal-body">
                        <p>What is your problem?</p>
                        <fieldset>
                            <input type="text" name="ticket" placeholder='I need you because...'>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Contact</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteTicket" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                    <button type="submit" form="deleteTicketForm" class="btn btn-danger">Delete</button>
                </div>   
            </div>
        </div>
    </div>
{% endblock main %}



{% block script %}
<script type="text/javascript">
    {% autoescape false %}
    var current_user = '{{current_user.username_user}}';
    var is_admin = '{{current_user.is_admin_user}}';
    var user_image = '{{picture}}';
    {% endautoescape %}

    function isAdmin(){
        return is_admin;
    }

    function getUsername() {
        return current_user;
    }

    function getImageUser(){
        return user_image;
    }

</script>
<script src="{{ url_for('static', filename='pc/js/support.js') }}" defer></script>
{% endblock script %}