flask/website/views/settings.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    send_from_directory,
    url_for,
    request
)
from flask_mobility.decorators import mobile_template
from ..models import ORM
from ..utils import Utils
from flask_login import current_user
from werkzeug.utils import secure_filename
from ..app import app
import os
import imghdr
import hashlib
from random import randint
from flask_login import current_user, login_required
from hashlib import sha256
from flask.helpers import flash

mod = Blueprint('settings', __name__)


@mod.route('/settings/', methods=['GET'])
@mobile_template("{mobile/Settings/}settings.html")
@login_required
def settings(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(
        template,
        devices=devices
    )


"""
ACCOUNT
"""


@mod.route('/settings/account/', methods=['GET'])
@mobile_template("{mobile/Settings/}account.html")
@login_required
def settings_account(template):
    files = os.listdir(app.config['UPLOAD_PATH'])
    devices = ORM.get_devices_by_username(current_user.username_user)
    subscription_name = ORM.get_subscription_name_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        files=files,
        subscription_name=subscription_name,
    )


@mod.route('/settings/account/update/', methods=['POST'])
@login_required
def settings_account_update():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    mail = result['email']
    mdp = result['password']
    code = result['postal-code']
    ville = result['town']
    rue = result['street']

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)
    if confirmpassword == password:
        validation, message = Utils.is_valid_change_account(mdp, tel, mail, ville, rue, code)
        if validation:
            ORM.update_user(mdp, tel, first, last, mail, ville, code, rue)
            flash(message, "success")
            return redirect(url_for('settings.settings_account'))

        flash(message, "error")
        return redirect(url_for('settings.settings_account'))

    flash("Incorrect Password. Changes were not applied!", "error")
    return redirect(url_for("settings.settings_account"))


'''
DEVICES
'''


@mod.route('/settings/device/', methods=['GET'])
@mobile_template("{mobile/Settings/}device.html")
@login_required
def settings_devices(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    selected = ORM.get_current_name_device_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        selected_device=selected
    )


@mod.route('/settings/devices/update/', methods=['GET', 'POST'])
@login_required
def settings_devices_update():
    name = request.form.get("name")
    movement = request.form.get("movement")
    delay = request.form.get("delay")

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)
    if confirmpassword == password:
        ORM.update_device_parameters(current_user.username_user, name)
        flash("Changes have been applied!", "success")
        return redirect(url_for("settings.settings_devices"))
    flash("Incorrect Password. Changes were not applied.", "error")
    return redirect(url_for("settings.settings_devices"))


'''
CONTACT
'''


@mod.route('/settings/contacts/', methods=['GET'])
@mobile_template("{mobile/Settings/}contacts.html")
@login_required
def settings_contact(template):
    contacts = ORM.get_contacts_by_user(current_user.username_user)
    devices = ORM.get_devices_by_username(current_user.username_user)
    number_contacts = ORM.get_number_of_contacts_by_username(current_user.username_user)

    return render_template(
        template,
        contacts=contacts,
        devices=devices,
        number=number_contacts
    )


@mod.route('/settings/contacts/update/', methods=['GET', 'POST'])
@mobile_template("{mobile/Settings/}update_contact.html")
@login_required
def settings_contact_update(template):
    result = request.form
    id_contact = result["id-contact"]
    action = result["action"]
    if action == "edit":
        contact = ORM.get_contact_by_id(id_contact)
        first = contact.firstname_contact
        last = contact.lastname_contact
        tel = contact.num_contact
        devices = ORM.get_devices_by_username(current_user.username_user)
        return render_template(template, id_contact=id_contact, first=first, last=last, tel=tel,
                               devices=devices)

    ORM.remove_contact(id_contact)
    return redirect(url_for('settings.settings_contact'))


@mod.route('/settings/contacts/update/check/', methods=['GET', 'POST'])
@login_required
def settings_contact_update_check():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    id_contact = result['id-contact']

    if first != "" and last !="":
        if Utils.is_valid_tel(tel):
            ORM.update_contact(tel, first, last, id_contact)
            flash("Contact has been updated.", "success")
        else:
            flash("Invalid phone number. Update failed.","error")
    else:
        flash("First name and Last name should not be empty. Update failed.","error")
    return redirect(url_for("settings.settings_contact"))


@mod.route('/settings/contacts/add/', methods=['GET'])
@mobile_template('{mobile/Settings/}add_contact.html')
@login_required
def settings_contact_add(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(template, devices=devices)


@mod.route('/settings/contacts/add/check/', methods=['GET', 'POST'])
@login_required
def settings_contact_add_check():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    device = ORM.get_current_num_device_by_username(current_user.username_user)
    img = '/static/pc/assets/avatar.png'

    if first != "" and last !="":
        if Utils.is_valid_tel(tel):
            ORM.new_contact(tel, first, last, img, device)
            flash("Contact has been added.", "success")
        else:
            flash("Invalid phone number.","error")
    else:
        flash("First name and Last name should not be empty.","error")
    return redirect(url_for("settings.settings_contact"))


'''
CREDIT CARD MOBILE
'''


@mod.route('/settings/card/', methods=['GET'])
@mobile_template("{mobile/Settings/}credit-card.html")
@login_required
def settings_card(template):
    return render_template(template)


'''
PAYMENT
'''


@mod.route('/settings/payment/', methods=['GET'])
@mobile_template("{mobile/Settings/}payment.html")
@login_required
def settings_payment(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(template, devices=devices)


@mod.route('/settings/payment/edit/', methods=['GET', 'POST'])
@mobile_template("{mobile/Settings/}edit_payment.html")
@login_required
def settings_payment_edit(template):
    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        devices = ORM.get_devices_by_username(current_user.username_user)
        return render_template(template, devices=devices)

    flash("Incorrect Password.", "error")
    return redirect(url_for("settings.settings_payment"))


@mod.route('/settings/payment/edit/check/', methods=['GET', 'POST'])
@login_required
def settings_payment_edit_check():
    number = request.form.get("number")
    holder_name = request.form.get("holder")
    expiration = request.form.get("expiration")
    cvv = request.form.get("cvv")

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        flash("Payment service is not available for the moment. Changes were not applies.", "error")
        return redirect(url_for('settings.settings_payment'))

    flash("Payment service is not available for the moment. Changes were not applies.", "error")
    return redirect(url_for('settings.settings_payment'))


@mod.route('/settings/subscription/', methods=['GET'])
@mobile_template("{mobile/Settings/}subscription.html")
@login_required
def settings_subscriptions(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    subscriptions = ORM.get_subscriptions()
    features = Utils.str_collon_to_list(ORM.get_subscriptions_features()[0])
    subscription_name = ORM.get_subscription_name_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        subscriptions=subscriptions,
        features=features,
        subscription_name=subscription_name
    )


@mod.route('/settings/subscription/update/', methods=['POST'])
@login_required
def settings_subscriptions_update():
    sub = request.form.get('sub')

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        if sub == "cancel":
            ORM.remove_device(current_user.selected_device)
            if not len(ORM.get_devices_by_username(current_user.username_user)):
                current_user.selected_device = None
                ORM.block_user(current_user.username_user)
            else:
                current_user.selected_device = ORM.get_devices_by_username(current_user.username_user)[0]

flask/website/templates/mobile/Settings/account.html
{% extends "mobile/base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename = 'mobile/css/Settings/account_parameters_update.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dropzone/dropzone.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename = 'mobile/css/Settings/profile-picture.css') }}">
{% endblock %}

{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
<div class="flex">
    <a href="{{ url_for('settings.settings') }}" class=" goback">
        <i class="fa fa-chevron-left"></i>
    </a>

    <h2>Your account</h2>
    <div class="main">
        <div class="user-profile">
            <form action="{{ url_for('settings.upload_files') }}" id="imageUpload" class="dropzone">

                <div class="img-avatar">
                    <img id='picture' src="{{ current_user.profile_picture_user }}" alt="your avatar">
                    <p>Current Picture</p>
                </div>
                <div class="dz-message" data-dz-message><span>Click here to upload images</span></div>
            </form>
        </div>
        <div class="account">
            <span>Registered on {{ current_user.date_creation_user }}</span>
            <div id="current-user" style="display: none">{{ current_user.username_user }}</div>
            <form action="{{ url_for('settings.settings_account_update') }}" id="update-account" method='POST'>

                <fieldset>
                    <legend>Password</legend>
                    <input class="form-input" type="password" name="password">
                </fieldset>

                <fieldset>
                    <legend>First name</legend>
                    <input class="form-input" type="text" name="first-name" value="{{ current_user.firstname_user }}">
                </fieldset>

                <fieldset>
                    <legend>Last name</legend>
                    <input class="form-input" type="text" name="last-name" value="{{ current_user.lastname_user }}">
                </fieldset>

                <fieldset>
                    <legend>Phone number</legend>
                    <input class="form-input" type="tel" name="phone" value="{{ current_user.num_user }}">
                </fieldset>

                <fieldset>
                    <legend>Email</legend>
                    <input class="form-input" type="email" name="email" value="{{ current_user.email_user }}">
                </fieldset>

                <fieldset>
                    <legend>Town</legend>
                    <input class="form-input" type="text" name="town" value="{{ current_user.town_user }}">
                </fieldset>

                <fieldset>
                    <legend>Street</legend>
                    <input class="form-input" type="text" name="street" value="{{ current_user.street_user }}">
                </fieldset>

                <fieldset>
                    <legend>Postal Code</legend>
                    <input class="form-input" type="text" name="postal-code" pattern="[0-9]{5}"
                        value="{{ current_user.postal_code_user }}">
                </fieldset>
                <div class="form-submit">
                    <!-- My Buttons -->
                    <a href="{{ url_for('settings.settings') }}">Cancel</a>
                    <button type="button" data-toggle="modal" data-target="#modalCenter">Update
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Enter your actual password to confirm changes.</p>
                    <fieldset class="modal-fd">
                        <input type="password" form="update-account" name="confirmpassword" placeholder='********'>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" form="update-account" class="btn btn-primary">Save changes</button>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {
        $('#picture').on('click', function () {
            $('#fileinput').trigger('click');
        });
    });

    $(function () {
        $('#fileinput').change(function () {
            var input = this;
            var url = $(this).val();
            var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
            if (input.files && input.files[0] && (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg")) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#picture').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }

        });

    });
</script>
<script src="{{ url_for('static', filename='dropzone/dropzone.min.js') }}"></script>
<script>

    Dropzone.options.imageUpload = {
        maxFiles: 1,
        acceptedFiles: ".jpeg,.jpg,.png,.gif",
        maxFilesize: 3,
        accept: function (file, done) {
            console.log("uploaded");
            done();
        },
        init: function () {
            this.on('addedfile', function (file) {
                if (this.files.length > 1) {
                    this.removeFile(this.files[0]);
                }
            });
            this.on("success", function () {
                console.log()
                var current_username = document.getElementById("current-user").textContent

                console.log("current username " + current_username);
                $.ajax({
                    url: "/api/user/profile/" + current_username,
                    success: function (result) {
                        document.getElementById("picture").src = result.response;
                        document.getElementById("img-profile").style.backgroundImage = "url('" + result.response + "')";
                    },
                    error: function (err) {
                    }
                });
            });
            this.on("maxfilesexceeded", function (file) {
                alert("No more files please!");
            });
        }
    };
</script>
{% endblock script %}

flask/website/templates/mobile/Settings/contacts.html
{% extends "mobile/base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename = 'mobile/css/Settings/contacts.css') }}">
{% endblock %}

{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
<div class="flex">        
    <a href="{{ url_for('settings.settings') }}" class="goback">
        <i class="fa fa-chevron-left"></i>
    </a>
    <section>
        <h3><i class="fa fa-bell"></i> Contacts to Call</h3>
        {% for contact in contacts %}
        <div class="contact">
            <form action="{{ url_for('settings.settings_contact_update') }}" id="update-contact" method='POST'>
                <div class="info">
                    <img src="{{ url_for('static', filename='pc/assets/avatar.png') }}" alt="your contact avatar">
                    <h4>{{contact.firstname_contact}} {{contact.lastname_contact}}</h4>
                </div>
                
                <input type="hidden" name="id-contact" value='{{contact.id_contact}}'>
               
                <div class="action">
                    <button type="submit" name="action" value="edit"><i class="fa fa-user-edit"></i></button>
                    <button type="submit" name="action" value="remove"><i class="fa fa-trash-alt"></i></button>
                </div>
            </form>
        </div>
        {% endfor %}
    </section>
    <div id="add-contact">
        <a href="{{ url_for('settings.settings_contact_add') }}">
            <i class="fa fa-plus"></i>
        </a>
    </div>
    
</div>
{% endblock main %}

{% block script %}
{% endblock script %}

flask/website/templates/mobile/Settings/device.html
{% extends "mobile/base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename = 'mobile/css/Settings/device.css') }}">
{% endblock %}

{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
<div class="flex">
    <a href="{{ url_for('settings.settings') }}" class="goback">
        <i class="fa fa-chevron-left"></i>
    </a>
    <section>
        <div class="flash">
            {% include "messages.html" %}
        </div>
        <h1>Your Device ({{selected_device}})</h1>
        <form action="{{ url_for('settings.settings_devices_update') }}" id="form-devices" method='POST'>
            <h3>Parameters</h3>
            <div class="slidecontainer group1">
                <label for="movement">
                    Minimum Movement Distance : <span id="value-movement"></span>m
                </label>
                <div>
                    <span>5m</span>
                    <input type="range" min="5" max="50" value="27" class="slider" id="movement">
                    <span>50m</span>
                </div>

            </div>
            <div class="slidecontainer group2">
                <label for="delay">
                    SMS Sending Delay : <span id="value-delay"></span>s
                </label>
                <div>
                    <span>20s</span>
                    <input type="range" min="20" max="120" value="70" class="slider" id="delay">
                    <span>120s</span>
                </div>
            </div>
            <div class="group3">
                <label for="name">
                    Device name :
                </label>
                <input type="text" name="name" value='{{selected_device}}'>
            </div>
            <div class="form-submit">
                <!-- My Buttons -->
                <a href="{{ url_for('settings.settings') }}">Cancel</a>
                <button type="button" data-toggle="modal" data-target="#modalCenterDevice">Update</button>
            </div>
        </form>
    </section>
    <!-- Bootstrap -->
    <div class="modal fade" id="modalCenterDevice" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitleDevice" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLongTitleDevice">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Enter your password to confirm changes.</p>
                    <fieldset class="modal-fd">
                        <input type="password" form="form-devices" name="confirmpassword" placeholder='********'>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" form="form-devices" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

{% block script %}
<script>
    var slider = document.getElementById("movement");
    var output = document.getElementById("value-movement");
    output.innerHTML = slider.value; // Display the default slider value

    // Update the current slider value (each time you drag the slider handle)
    slider.oninput = function() {
        output.innerHTML = this.value;
    }

    var slider2 = document.getElementById("delay");
    var output2 = document.getElementById("value-delay");
    output2.innerHTML = slider2.value; // Display the default slider value

    // Update the current slider value (each time you drag the slider handle)
    slider2.oninput = function() {
        output2.innerHTML = this.value;
    }
</script>
{% endblock script %}

flask/website/templates/mobile/Settings/payment.html
{% extends "mobile/base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename = 'mobile/css/Settings/payment.css') }}">
{% endblock %}

{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
<div class="flex">
    <a href="{{ url_for('settings.settings') }}"" class=" goback">
        <i class="fa fa-chevron-left"></i>
    </a>
    <section class='payment'>
        <div class="flash">
            {% include "messages.html" %}
        </div>
        <h3>Your Credit Card</h3>
        <div class='credit-card'>
            <div class="haut">
                <img src="{{ url_for('static', filename='pc/assets/mastercard.png') }}" alt="mastercard logo">
            </div>
            <div class="bas">
                <p>**** **** **** 2562</p>
                <p>03/2018</p>
            </div>
        </div>
    
        <a href="#" data-toggle="modal" data-target="#modalCenter"><i class="fa fa-chevron-right"></i></a>
    </section>
    
    <div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ url_for('settings.settings_payment_edit') }}" method='POST'>
                    <div class="modal-body">
                        <p>Enter your password to acceed.</p>
                        <fieldset class='modal-fd'>
                            <input type="password" name="confirmpassword" placeholder='********'>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Pursue</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flask/website/templates/mobile/Settings/subscription.html
{% extends "mobile/base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename = 'mobile/css/Settings/subscription.css') }}">
{% endblock %}

{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
<div class="flex">
    <a href="{{ url_for('settings.settings') }}" class=" goback">
        <i class="fa fa-chevron-left"></i>
    </a>
    <div class="flash">
        {% include "messages.html" %}
    </div>
    
    <form action="{{ url_for('settings.settings_subscriptions_update') }}" id="form-sub" method='POST'>
        {% for sub in subscriptions %}
            <section class='section-sub'>
                <h2>{{sub.name_subscription}}</h2>
                <div>
                <h4>{{sub.localisation_subscription}}</h4>
                    <ul>
                        {% for feature in  features %}
                            {% if sub.name_subscription == "France" and feature == "World Wide Localisation"%}
                                <s>{{feature}}</s>
                            {% else %}
                                <li>{{feature}}</li>
                            {% endif %}
                        {% endfor %}
                    </ul> 
                </div>
                
                <div class="sub-radio">
                    {% if subscription_name != sub.name_subscription %}
                    <button type="button" onclick="checkRadio(this)" data-toggle="modal" data-target="#modalCenter">
                        <input type="radio" name="sub" value="{{sub.name_subscription}}">
                        Choose this plan - €{{sub.price_subscription}}/mo
                    </button>
                    {% else %}
                    <button type="button">Your current plan</button>
                    {% endif %}
                </div>
            </section>
        {% endfor %}
        <section class='cancel'>
            <h2>Cancel</h2>
            <div>
                <h4>Cancel your subscription</h4>
                <p>Warning, this is an important action. Select this option will remove your privileges.</p>
                <p>Please send your BiKeeper at 15 Avenue de Paris if you want to leave our community.</p>
            </div>

            <div class="sub-radio">
                <button type="button" onclick="checkRadio(this)" data-toggle="modal" data-target="#modalCenter">
                    <input type="radio" name="sub" value="cancel">
                    Cancel
                </button>
            </div>
        </section>
    </form>
</div>

<div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLongTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
                <p>Please enter your password to confirm.</p>
                <fieldset class="modal-fd">
                    <input type="password" form="form-sub" name="confirmpassword" placeholder='********'>
                </fieldset>
            </div>
            <div class="modal-footer">
                <button type="submit" form="form-sub" class="btn btn-danger">Yes</button>
                <button type="button" class="btn btn-success" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

{% block script %}
<script src="{{ url_for('static', filename='pc/js/subscription.js') }}"></script>
{% endblock script %}