flask/website/views/admin.py
from flask import (
	Blueprint,
	render_template,
	session,
	redirect,
	abort,
	url_for,
	request
)
from flask_mobility.decorators import mobile_template
from flask_login import login_required, login_user, logout_user, current_user
from functools import wraps
from ..models import ORM

mod = Blueprint('admin', __name__)


def admin_required(f):
	@wraps(f)
	def wrap(*args, **kwargs):
		if not current_user.is_admin_user:
			abort(403, description="Can't access an admin page as user")
		return f(*args, **kwargs)

	return wrap


@mod.route('/admin/access', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_access.html")
@login_required
@admin_required
def admin_access(template):
	return render_template(template)


@mod.route('/admin/home', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_home.html")
@login_required
@admin_required
def admin_home(template):
	return render_template(
		template,
		nb_users=ORM.get_number_of_user(),
		tt_data=ORM.get_space_used_database(),
		nb_ticket=ORM.get_number_open_ticket(),
		nb_bikeeper=ORM.get_number_of_bikeeper()
	)


@mod.route('/admin/support', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_support.html")
@login_required
@admin_required
def admin_support(template):
	return render_template(template)


@mod.route('/admin/platform', methods=["GET"])
@login_required
@admin_required
def platform():
	return render_template('admin_platform.html')

flask/website/views/home.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    request,
    url_for
)
from flask_mobility.decorators import mobile_template
from flask_login import login_required, current_user
from ..models import ORM
from ..utils import Utils

mod = Blueprint('home', __name__)


@mod.route('/home/', methods=['GET', 'POST'])
@mobile_template('{mobile/User/}home.html')
@login_required
def home(template):
    ip_address = request.remote_addr
    ORM.log_ip(ip_address)
    devices = ORM.get_devices_by_username(current_user.username_user)
    selected_device = current_user.selected_device
    return render_template(
        template,
        devices = devices,
        selected_device=selected_device
        )


@mod.route('/localisation/', methods=['GET', 'POST'])
@login_required
def localisation():
    return render_template(
        "mobile/User/localisation.html"
        )

flask/website/views/stats.py
import json

from flask import (
	Blueprint,
	render_template,
	session,
	redirect,
	url_for,
	request,
	current_app
)
from flask_login import current_user, login_required

from ..models import ORM
from flask_mobility.decorators import mobile_template
from flask.helpers import flash

mod = Blueprint("stats", __name__)


@login_required
@mod.route('/statistics/', methods=['GET', 'POST'])
@mobile_template('{mobile/User/}stats.html')
def statistics(template):
	search_user = request.form.get('search_user', default=None, type=str)

	if search_user is not None:  # ADMIN
		res = ORM.search_user(search_user)
		if len(res)!=0:
			res = res [0]
			devices = ORM.get_devices_by_username(res.username_user)
			price = ORM.get_price_from_subscription_name(res.name_subscription)
			is_blocked = ORM.is_blocked_account_user(res.username_user)
					
		else:
			flash("User not found.","error")
			return redirect(url_for('stats.statistics'))

		return render_template(
			template,
			username=res.username_user,
			phone=res.num_user,
			street=res.street_user,
			town=res.town_user,
			devices=devices,
			picture=res.profile_picture_user,
			date=res.date_creation_user,
			subscription=res.name_subscription,
			price=price,
			is_blocked=is_blocked
		)

	else:
		return render_template(
			template,
			username='',
			devices=ORM.get_devices_by_username(current_user.username_user),
			id_device =current_user.selected_device
		)

@login_required
@mod.route('/statistics/unblock', methods=['GET', 'POST'])
def statistics_unblock():
	username = request.form.get("username")
	if ORM.get_number_of_devices_by_username(username) > 0:
		ORM.unblock_user(username)
	else:
		flash("This user has left our community. He cannot be unblocked.","error")
	return redirect(url_for('stats.statistics'))

@login_required
@mod.route('/statistics/block', methods=['GET', 'POST'])
def statistics_block():
	username = request.form.get("username")
	ORM.block_user(username)
	return redirect(url_for('stats.statistics'))

flask/website/views/support.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    url_for,
    request,
    Response
)
from ..app import db
from ..models import ORM, TICKET, USER, MESSAGE
from flask_mobility.decorators import mobile_template
from flask_login import login_required, current_user

mod = Blueprint('support', __name__)

@login_required
@mod.route('/support/', methods=['GET'])
@mobile_template('{mobile/User/}support.html')
def support(template):
    messages = {}

    if not current_user.is_admin_user:
        open_tickets_user = ORM.get_open_ticket_user(current_user.username_user)

        if len(open_tickets_user) != 0:
            for ticket in open_tickets_user:
                messages[ticket.id_ticket] = ORM.get_message_by_ticket_id(ticket.id_ticket)
    else:
        open_tickets = ORM.get_open_ticket()
        for ticket in open_tickets:
            messages[ticket.id_ticket] = ORM.get_message_by_ticket_id(ticket.id_ticket)
    
    last_messages = {}
    for i_mes in messages.keys():
        last_messages[i_mes] = ORM.get_last_message_by_ticket_id(i_mes)
    
    return render_template(
        template,
        messages = messages,
        picture = ORM.get_picture_message_from_username(current_user.username_user),
        last_messages= last_messages,
        devices = ORM.get_devices_by_username(current_user.username_user)
    )

@login_required
@mod.route('/support/<int:id_ticket>/', methods=['GET'])
def support_message(id_ticket):
    return render_template(
        'mobile/User/support-bis.html',
        id_ticket = id_ticket,
        messages = ORM.get_message_by_ticket_id(id_ticket),
        picture = ORM.get_picture_message_from_username(current_user.username_user),
        )

@login_required
@mod.route('/support/message/new', methods=['POST'])
def support_message_new():
    if request.method == 'POST':
        contenu_message = request.json['content']
        is_admin = request.json['is_admin']
        date = request.json['date']
        id_ticket = request.json['id_ticket']
        username = request.json['username']

        msg = MESSAGE(is_admin, date, contenu_message, id_ticket, username)
        db.session.add(msg)
        db.session.commit()

        return Response(status=200)

@login_required
@mod.route('/support/ticket/new', methods=['POST'])
def support_new_ticket():
    title = request.form.get('ticket')
    if not current_user.is_authenticated:
        return redirect(url_for('login'))
    user = current_user.username_user
    ticket = TICKET(title,0,user)
    db.session.add(ticket)
    db.session.commit()
    return redirect(url_for('support.support'))


@login_required
@mod.route('/support/ticket/close', methods=['POST'])
def support_delete_ticket():
    id_ticket = request.form.get('id_ticket')
    ORM.remove_tickets_by_id(id_ticket)
    return redirect(url_for('support.support'))


@login_required
@mod.route('/support/ticket/close/<int:id_ticket>', methods=['POST'])
def support_delete_ticket_by_id(id_ticket):
    ORM.remove_tickets_by_id(id_ticket)
    return redirect(url_for('support.support'))


@login_required
@mod.route('/support/<int:user_id>/tickets/all', methods=['GET'])
def get_user_tickets_by_id(user_id):
    res = "<ul>"
    list_ticket = ORM.get_user_tickets(user_id)
    for ticket in list_ticket:
        res += f"<li><p>ID ticket: {ticket.id_ticket}</p>" \
               f"<p>Title ticket: {ticket.title_ticket}" \
               f"<p>Is closed?: {ticket.is_closed_ticket}</p></li>"
    res += "</ul>"
    return res

@login_required
@mod.route('/support/tickets/open/all', methods=['GET'])
def get_open_tickets():
    res = "<ul>"
    open_tickets = ORM.get_open_ticket()
    for ticket in open_tickets:
        res += f"<li><p>ID ticket: {ticket.id_ticket}</p>" \
               f"<p>Title ticket: {ticket.title_ticket}" \
               f"<p>Is closed?: {ticket.is_closed_ticket}</p></li>"
    res += "</ul>"
    return res

flask/website/views/users.py
from ..models import USER
from ..models import ORM
from flask import Blueprint
from flask_mobility.decorators import mobile_template

mod = Blueprint('user', __name__)


@mod.route('/users/<string:user_id>', methods=['GET'])
def user_page(user_id):
    user = ORM.get_user(user_id)
    return f"<p>Username: {user.username_user}</p>" \
           f"<p>Number: {user.num_user}</p>" \
           f"<p>Firstname: {user.firstname_user}</p>" \
           f"<p>Lastname: {user.lastname_user}</p>" \
           f"<p>Email: {user.email_user}</p>" \
           f"<p>Town: {user.town_user}</p>" \
           f"<p>Postal code: {user.postal_code_user}</p>" \
           f"<p>Street: {user.street_user}</p>"

flask/website/templates/mobile/User/faq.html
{% extends "mobile/base.html" %}
{% block header %}
        <div class="logo">
            <a href="/home/"><img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
            <h1>BiKeeper</h1></a>
        </div>
        {% include "components/mobile-sidebar.html" %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mobile/css/User/faq.css') }}">
        <nav onclick="openNav()"><img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu"></nav>
{% endblock %}
{% block main %}


<h2 id="title">FAQ</h2>


{% for category in topic %}

<div class="accordion accordion-flush" id="faq">
  	<div class="accordion-item">
    	<h2 class="accordion-header" id="{{category}}">
      		<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#i-{{category}}" aria-expanded="false" aria-controls="i-{{category}}">
        		{{category}}
      		</button>
    	</h2>
    	<div id="i-{{category}}" class="accordion-collapse collapse box" aria-labelledby="{{category}}" data-bs-parent="#faq">
    		{% for question in data %}
			{% if data[question]["topic"] == category %}
      		<div class="container-fluid">
				<h4 class="question">{{question}}</h4><br>
				<p class="anwser">{{data[question]["anwser"]}}</p>
				{% if data[question]["optional-link"]!=""  %}
				<a href="{{data[question]['optional-link']}}" class="link">Cliquez ici !</a>
				{% endif %}
			</div>
      		{% endif %}
			{% endfor %}
    	</div>
  	</div>
</div>

{% endfor %}



{% endblock %}

flask/website/templates/mobile/User/home.html
{% extends "mobile/base.html" %}
{% from "components/mobile-btn-large.html" import newLargeButton with context %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mobile/css/User/home-mobile.css') }}">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
crossorigin=""/>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.css">
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
{% endblock %}

{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
<div class="container">

    {{ newLargeButton("/localisation/", "Find your motorbike", "mobile/assets/location_outline.png", "find") }}

    <div class="row">
        <div class="col-6">
            <div class="card" style="width: 18rem;">
                <div class="cercle">
                    <span id="alerts"></span>
                </div>
                <img src="{{ url_for('static', filename='mobile/assets/alert.png') }}" class="card-img-top" alt="alert">
                <div class="card-body">
                    <h5 class="card-title">Alerts</h5>
                    <a href="{{ url_for('stats.statistics') }}" class="link">All notifications</a>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card" style="width: 18rem;">
                <div class="cercle">
                    <span id="rides"></span>
                </div>
                <img src="{{ url_for('static', filename='mobile/assets/moto1.png') }}" class="card-img-top" alt="moto">
                <div class="card-body">
                    <h5 class="card-title">Rides</h5>
                    <a href="{{ url_for('stats.statistics') }}" class="link">See your courses</a>
                </div>
            </div>
        </div>
    </div>

    <h2>Weekly Activity</h2>

    <canvas id="activityChart"></canvas>

</div>
{% endblock %}

{% block script %}
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
                integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
                crossorigin=""></script>
<script>
    {% autoescape false %}
    const username_home = '{{ current_user.username_user }}';
    const selected_device = '{{ selected_device }}';
    {% endautoescape %}
</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.bundle.min.js"></script>
<script src="{{ url_for('static', filename='pc/js/home_chart.js') }}"></script>
<script src="{{ url_for('static', filename='pc/js/home_notifications.js') }}"></script>
{% endblock %}

flask/website/templates/mobile/User/localisation.html
{% extends "mobile/base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/localisation-mobile.css') }}">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
        integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
        crossorigin=""/>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
{% endblock %}


{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-2">
                <a href="{{ url_for('home.home') }}">
                    <i class="fa fa-chevron-left"></i>
                </a>
            </div>
            <div class="col-8">Localisation</div>
        </div>
    </div>
    <div class="container-fluid">
        
    </div>
    <div id="map">
        <!-- Ici s'affichera la carte -->
    </div>
{% endblock %}


{% block script %}
<script>
    {% autoescape false %}
    const username_home = '{{ current_user.username_user }}';
    const selected_device = '{{ current_user.selected_device }}';
    {% endautoescape %}
</script>
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
        integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
        crossorigin=""></script>
<script src="{{ url_for('static', filename='pc/js/home_map.js') }}"></script>
{% endblock %}

flask/website/templates/mobile/User/stats.html
{% extends "mobile/base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">

<!-- Import Leaflet CSS Style Sheet -->
<link rel="stylesheet" href="https://npmcdn.com/leaflet@1.0.0-rc.2/dist/leaflet.css"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;500&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/statistic-mobile.css') }}">
{% endblock %}


{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
<div class="flex">
        <section class='group1'>
            <h2>User Data</h2>  
            <div id="data" class='user-data'>      
                <div class='bikeeper-data'>
                    <img src="" alt="battery" id="battery-img">
                    <p id="is-charging"></p>
                </div>

                <ul>
                    <li><h6>Last Ride:</h6> <span id="last-ride">DATE</span></li>
                    <li><h6>Last Ride Duration:</h6> <span id="last-ride-duration">TIME</span></li>
                </ul>
            </div>
        </section>

        <section class='group2'>
            <div id="filters" class="filters">
                <h2>Filters</h2>
                <form class='filters'>
                    <div class='ride-date'>
                        <label for="ride-date">Ride Date: </label>
                        <input onchange="loadDateBikeepers()" type="date" name="ride-date" id="ride-date">
                    </div>
                    <div class='device-number'>
                        <label for="device-number">Device Number: </label>
                        <select onchange="createTimelineElements();loadRides()" name="device-number"
                                id="device-number">
                        </select>
                    </div>
                    <div class='ride-number'>
                        <label for="ride-number">Ride Number: </label>
                        <select onchange="displayRideData()" name="ride-number" id="ride-number">
                        </select>
                    </div>
                </form>
            </div>
            <div id="timeline" class="container-timeline">
                <h2>Timeline</h2>
                <div class="timeline">
                    
                </div>
            </div>

        </section>

        <section class='group3'>
            <div class="graph1">
                <div class="canvas1">
                    <canvas id="speed"></canvas>
                </div>
                <div class="info1">
                    <ul>
                        <li>Max Speed: <span id="max-speed"> - </span>km/h</li>
                        <li>Average Speed: <span id="average-speed"> - </span>km/h</li>
                    </ul>
                </div>
            </div>

            <div class="graph2">
                <div class="canvas2">
                    <canvas id="angle"></canvas>
                </div>
                <div class="info2">
                    <ul>
                        <li>Max Angle: <span id="max-angle"> - </span>°</li>
                        <li>Average Angle: <span id="average-angle"> - </span>°</li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="group5">
            <div class="container-fluid">
                <div class="parked park"></div>
            </div>
        </section>

        <section class="group4">
            <form action="{{ request.url }}" method='GET'>
                <div class="btn-container">
                    <input type="radio" name="local" id="local" checked hidden/>
                    <label for="local">Local</label>
                    <input type="radio" name="online" id="online" hidden/>
                    <label for="online">Online</label>
                </div>
            </form>
            <div id="my_osm_widget_map"></div>
            <div id="temp"></div>
        </section>
</div>
{% endblock %}

{% block script %}
<!-- Import Leaflet JS Library -->
<script src="https://npmcdn.com/leaflet@1.0.0-rc.2/dist/leaflet.js"></script>
<!-- Import Autocomplete JS Library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.devbridge-autocomplete/1.2.26/jquery.autocomplete.min.js"></script>
<script>
    {% autoescape false %}
    let username_stats = '{{ current_user.username_user }}';
    {% endautoescape %}

    $('#search_user').autocomplete({ // show suggestions when searching users as admin
        serviceUrl: '/api/bikeeper/search_user/' + document.getElementById('search_user').value,
        dataType: 'json',
    });
    if (document.getElementById("user-name") !== null) { // for admin page
        username_stats = document.getElementById("user-name").innerText;
    }
</script>


<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.bundle.min.js"></script>
<script src="{{ url_for('static', filename='pc/js/stats.js') }}"></script>
{% endblock %}

flask/website/templates/mobile/User/support-bis.html
{% extends "mobile/base.html" %}

        {% block header %}
        <div class="logo">
            <a href="/home/"><img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
            <h1>BiKeeper</h1></a>
        </div>
        {% include "components/mobile-sidebar.html" %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/support-mobile.css') }}">
        <!-- Use any element to open/show the overlay navigation menu -->
        <nav onclick="openNav()"><img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu"></nav>
        {% endblock %}

        {% block main %}
        <div class="container">
            <div class="row">
                <div class="col-2"><a href="/support/"><i class="fa fa-chevron-left"></i></a></div>
                <div class="col-8">TICKET #{{ id_ticket }}</div>
                {% if current_user.is_admin_user %}
                
                <div class="col-1 check">
                    <form id="deleteTicketForm" action="{{ url_for('support.support_delete_ticket') }}/{{ id_ticket }}" method="POST">
                        <button type="submit" id="btn-close">
                            <i class="fa fa-check"></i>
                        </button>
                    </form>
                </div>
                
                {% endif %}
            </div>
        </div>
        <section class='chat'>
            <div class="container" id="chat-{{ id_ticket }}"></div>
    
        </section>
        <div class="blank"></div>



        <div class="container-fluid" id="input-message">
            <div class="row">
                <div class="col-8"><input type="text" value="Write your message" name="msg" id="msg"></div>
                <div class="col-2"><button type="button"><i class="fa fa-paperclip"></i></button></div>
                <div class="col-2"><button type="submit" class="submit" id="send-msg"><i class="fa fa-paper-plane"></i></button></div>
            </div>
        </div>






    {% endblock %}


{% block script %}
<script type="text/javascript">
    {% autoescape false %}
    var current_user = '{{current_user.username_user}}';
    var is_admin = '{{current_user.is_admin_user}}';
    var user_image = '{{picture}}';
    {% endautoescape %}

    function isAdmin(){
        return is_admin;
    }

    function getUsername() {
        return current_user;
    }

    function getImageUser(){
        return user_image;
    }
    function checkRadioButton(elem) {
        elem.nextSibling.nextSibling.checked=true
    }

</script>
<script src="{{ url_for('static', filename='mobile/js/support.js') }}" defer></script>
{% endblock script %}

flask/website/templates/mobile/User/support.html
{% extends "mobile/base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/support-mobile.css') }}">
{% endblock %}

{% block header %}
{% include "components/mobile-header.html" %}
{% endblock %}

    
{% block main %}
<section class='tickets'>
    {% if not current_user.is_admin_user %}
    <a href="{{ url_for('home.home') }}" class="goback">
    {% else %}
    <a href="{{ url_for('admin.admin_home') }}" class="goback">
    {% endif %}
      <i class="fa fa-chevron-left"></i>
    </a>
    <div>
        <div class="container">
            <div class="container-fluid">
                <h3>TICKETS</h3>
            </div>
        </div>
        <div class="container">
            <ul class="nav">
            {% for numero in messages.keys() %}
            <div class="container-fluid tckt">
                <li onclick="" >
                    <a href="/support/{{ numero }}/" class="tckt-id">
                        Ticket#{{ numero }}
                    </a>
                    <p class="lst-msg">{{ last_messages[numero]["content"]  }}</p>
                </li>
            </div>
                
            {% endfor %}
        </ul>
        </div>
        

        

        {% if not current_user.is_admin_user %}
        <button type="button" class="btn btn-primary why-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Nous contacter
        </button>
        {% endif %}



        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Pourquoi nous contactez-vous ?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <form action="{{ url_for('support.support_new_ticket') }}" method='POST'>
                  <div class="modal-body">
                    <fieldset>
                        <input type="text" name="ticket" placeholder='I need you because...'>
                    </fieldset>
                  </div>
                  <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Valider</button>
                  </div>
              </form>
            </div>
          </div>
        </div>
    </div>
</section>

{% endblock main %}






{% block script %}
<script type="text/javascript">
        {% autoescape false %}
        var current_user = '{{current_user.username_user}}';
        var is_admin = '{{current_user.is_admin_user}}';
        var user_image = '{{picture}}';
        {% endautoescape %}

        function isAdmin(){
            return is_admin;
        }

        function getUsername() {
            return current_user;
        }

        function getImageUser(){
            return user_image;
        }

</script>
<script src="{{ url_for('static', filename='pc/js/support.js') }}" defer></script>
{% endblock script %}