flask/website/views/admin.py
from flask import (
	Blueprint,
	render_template,
	session,
	redirect,
	abort,
	url_for,
	request
)
from flask_mobility.decorators import mobile_template
from flask_login import login_required, login_user, logout_user, current_user
from functools import wraps
from ..models import ORM

mod = Blueprint('admin', __name__)


def admin_required(f):
	@wraps(f)
	def wrap(*args, **kwargs):
		if not current_user.is_admin_user:
			abort(403, description="Can't access an admin page as user")
		return f(*args, **kwargs)

	return wrap


@mod.route('/admin/access', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_access.html")
@login_required
@admin_required
def admin_access(template):
	return render_template(template)


@mod.route('/admin/home', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_home.html")
@login_required
@admin_required
def admin_home(template):
	return render_template(
		template,
		nb_users=ORM.get_number_of_user(),
		tt_data=ORM.get_space_used_database(),
		nb_ticket=ORM.get_number_open_ticket(),
		nb_bikeeper=ORM.get_number_of_bikeeper()
	)


@mod.route('/admin/support', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_support.html")
@login_required
@admin_required
def admin_support(template):
	return render_template(template)


@mod.route('/admin/platform', methods=["GET"])
@login_required
@admin_required
def platform():
	return render_template('admin_platform.html')

flask/website/views/logout.py
from flask import Blueprint, render_template, request, redirect, url_for, escape
from flask_login import login_required, logout_user
from flask_mobility.decorators import mobile_template

mod = Blueprint('logout', __name__)


@mod.route("/logout/")
@login_required
def logout():
    logout_user()
    return redirect(url_for('index.index'))

flask/website/views/settings.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    send_from_directory,
    url_for,
    request
)
from flask_mobility.decorators import mobile_template
from ..models import ORM
from ..utils import Utils
from flask_login import current_user
from werkzeug.utils import secure_filename
from ..app import app
import os
import imghdr
import hashlib
from random import randint
from flask_login import current_user, login_required
from hashlib import sha256
from flask.helpers import flash

mod = Blueprint('settings', __name__)


@mod.route('/settings/', methods=['GET'])
@mobile_template("{mobile/Settings/}settings.html")
@login_required
def settings(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(
        template,
        devices=devices
    )


"""
ACCOUNT
"""


@mod.route('/settings/account/', methods=['GET'])
@mobile_template("{mobile/Settings/}account.html")
@login_required
def settings_account(template):
    files = os.listdir(app.config['UPLOAD_PATH'])
    devices = ORM.get_devices_by_username(current_user.username_user)
    subscription_name = ORM.get_subscription_name_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        files=files,
        subscription_name=subscription_name,
    )


@mod.route('/settings/account/update/', methods=['POST'])
@login_required
def settings_account_update():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    mail = result['email']
    mdp = result['password']
    code = result['postal-code']
    ville = result['town']
    rue = result['street']

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)
    if confirmpassword == password:
        validation, message = Utils.is_valid_change_account(mdp, tel, mail, ville, rue, code)
        if validation:
            ORM.update_user(mdp, tel, first, last, mail, ville, code, rue)
            flash(message, "success")
            return redirect(url_for('settings.settings_account'))

        flash(message, "error")
        return redirect(url_for('settings.settings_account'))

    flash("Incorrect Password. Changes were not applied!", "error")
    return redirect(url_for("settings.settings_account"))


'''
DEVICES
'''


@mod.route('/settings/device/', methods=['GET'])
@mobile_template("{mobile/Settings/}device.html")
@login_required
def settings_devices(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    selected = ORM.get_current_name_device_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        selected_device=selected
    )


@mod.route('/settings/devices/update/', methods=['GET', 'POST'])
@login_required
def settings_devices_update():
    name = request.form.get("name")
    movement = request.form.get("movement")
    delay = request.form.get("delay")

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)
    if confirmpassword == password:
        ORM.update_device_parameters(current_user.username_user, name)
        flash("Changes have been applied!", "success")
        return redirect(url_for("settings.settings_devices"))
    flash("Incorrect Password. Changes were not applied.", "error")
    return redirect(url_for("settings.settings_devices"))


'''
CONTACT
'''


@mod.route('/settings/contacts/', methods=['GET'])
@mobile_template("{mobile/Settings/}contacts.html")
@login_required
def settings_contact(template):
    contacts = ORM.get_contacts_by_user(current_user.username_user)
    devices = ORM.get_devices_by_username(current_user.username_user)
    number_contacts = ORM.get_number_of_contacts_by_username(current_user.username_user)

    return render_template(
        template,
        contacts=contacts,
        devices=devices,
        number=number_contacts
    )


@mod.route('/settings/contacts/update/', methods=['GET', 'POST'])
@mobile_template("{mobile/Settings/}update_contact.html")
@login_required
def settings_contact_update(template):
    result = request.form
    id_contact = result["id-contact"]
    action = result["action"]
    if action == "edit":
        contact = ORM.get_contact_by_id(id_contact)
        first = contact.firstname_contact
        last = contact.lastname_contact
        tel = contact.num_contact
        devices = ORM.get_devices_by_username(current_user.username_user)
        return render_template(template, id_contact=id_contact, first=first, last=last, tel=tel,
                               devices=devices)

    ORM.remove_contact(id_contact)
    return redirect(url_for('settings.settings_contact'))


@mod.route('/settings/contacts/update/check/', methods=['GET', 'POST'])
@login_required
def settings_contact_update_check():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    id_contact = result['id-contact']

    if first != "" and last !="":
        if Utils.is_valid_tel(tel):
            ORM.update_contact(tel, first, last, id_contact)
            flash("Contact has been updated.", "success")
        else:
            flash("Invalid phone number. Update failed.","error")
    else:
        flash("First name and Last name should not be empty. Update failed.","error")
    return redirect(url_for("settings.settings_contact"))


@mod.route('/settings/contacts/add/', methods=['GET'])
@mobile_template('{mobile/Settings/}add_contact.html')
@login_required
def settings_contact_add(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(template, devices=devices)


@mod.route('/settings/contacts/add/check/', methods=['GET', 'POST'])
@login_required
def settings_contact_add_check():
    result = request.form
    first = result['first-name']
    last = result['last-name']
    tel = result['phone']
    device = ORM.get_current_num_device_by_username(current_user.username_user)
    img = '/static/pc/assets/avatar.png'

    if first != "" and last !="":
        if Utils.is_valid_tel(tel):
            ORM.new_contact(tel, first, last, img, device)
            flash("Contact has been added.", "success")
        else:
            flash("Invalid phone number.","error")
    else:
        flash("First name and Last name should not be empty.","error")
    return redirect(url_for("settings.settings_contact"))


'''
CREDIT CARD MOBILE
'''


@mod.route('/settings/card/', methods=['GET'])
@mobile_template("{mobile/Settings/}credit-card.html")
@login_required
def settings_card(template):
    return render_template(template)


'''
PAYMENT
'''


@mod.route('/settings/payment/', methods=['GET'])
@mobile_template("{mobile/Settings/}payment.html")
@login_required
def settings_payment(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    return render_template(template, devices=devices)


@mod.route('/settings/payment/edit/', methods=['GET', 'POST'])
@mobile_template("{mobile/Settings/}edit_payment.html")
@login_required
def settings_payment_edit(template):
    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        devices = ORM.get_devices_by_username(current_user.username_user)
        return render_template(template, devices=devices)

    flash("Incorrect Password.", "error")
    return redirect(url_for("settings.settings_payment"))


@mod.route('/settings/payment/edit/check/', methods=['GET', 'POST'])
@login_required
def settings_payment_edit_check():
    number = request.form.get("number")
    holder_name = request.form.get("holder")
    expiration = request.form.get("expiration")
    cvv = request.form.get("cvv")

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        flash("Payment service is not available for the moment. Changes were not applies.", "error")
        return redirect(url_for('settings.settings_payment'))

    flash("Payment service is not available for the moment. Changes were not applies.", "error")
    return redirect(url_for('settings.settings_payment'))


@mod.route('/settings/subscription/', methods=['GET'])
@mobile_template("{mobile/Settings/}subscription.html")
@login_required
def settings_subscriptions(template):
    devices = ORM.get_devices_by_username(current_user.username_user)
    subscriptions = ORM.get_subscriptions()
    features = Utils.str_collon_to_list(ORM.get_subscriptions_features()[0])
    subscription_name = ORM.get_subscription_name_by_username(current_user.username_user)

    return render_template(
        template,
        devices=devices,
        subscriptions=subscriptions,
        features=features,
        subscription_name=subscription_name
    )


@mod.route('/settings/subscription/update/', methods=['POST'])
@login_required
def settings_subscriptions_update():
    sub = request.form.get('sub')

    confirmpassword = Utils.get_encrypt_password(request.form.get("confirmpassword"))
    password = ORM.get_password_user_by_username(current_user.username_user)

    if confirmpassword == password:
        if sub == "cancel":
            ORM.remove_device(current_user.selected_device)
            if not len(ORM.get_devices_by_username(current_user.username_user)):
                current_user.selected_device = None
                ORM.block_user(current_user.username_user)
            else:
                current_user.selected_device = ORM.get_devices_by_username(current_user.username_user)[0]

flask/website/views/sidebar.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    url_for,
    request
)
from flask_mobility.decorators import mobile_template
from ..models import ORM
from flask_login import current_user, login_required

mod = Blueprint('sidebar', __name__)

@login_required
@mod.route("/sidebar/device/change/", methods=['GET', 'POST'])
def sidebar_device_change():
    number = request.form.get("device_change")
    user = current_user.username_user
    ORM.update_user_selected_device(number, user)
    return(redirect(url_for('home.home')))

    

flask/website/templates/components/footer.html
<footer class='footer'>

    <div class='footer-left'>

        <h3>Bi<span>Keeper</span></h3>

        <p class='footer-links'>
            <a href="{{ url_for('login.login')}}" class='link-1'>Get a BiKeeper device</a>

            <a href='contact@bikeeper.fr'>Contact us</a>
        </p>

        <p class='footer-name'>BiKeeper Company © 2020</p>
    </div>

    <div class='footer-center'>

        <div>
            <p><span>16 rue d'Issoudun</span> 45160, Olivet, France</p>
        </div>

        <div class='footer-contact-tel'>
            <p>06 57 72 24 61</p>
        </div>

        <div class='footer-contact-mail'>
            <p><a href='mailto:contact@bikeeper.fr'>contact@bikeeper.fr</a></p>
        </div>

    </div>

    <div class='footer-right'>

        <p class='footer-about'>
            <span>A propos de nous</span>BiKeeper est une société créée en 2020. Nous avons pour vocation la sécurité d'autrui et de leurs biens à travers des dipositifs antivols !
        </p>

    </div>

</footer>

flask/website/templates/components/header.html
<header class="base">
    <div>
        {% if not current_user.is_admin_user %}
        <a href="{{ url_for('home.home') }}">
        {% else %}
        <a href="{{ url_for('admin.admin_home') }}">
        {% endif %}
            <img src="{{ url_for('static', filename='pc/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
        </a>
        <span>BiKeeper</span>
    </div>
    <div class="login">
        {% if current_user.is_authenticated %}
            <div class="dropdown profile show">
                <a class="dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div id='img-profile' style="background-image: url({{ current_user.profile_picture_user }});"></div>
                    <span>{{ current_user.username_user }}</span>
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    {% if not current_user.is_admin_user %}
                    <a href="{{ url_for('settings.settings_account')}}" class="dropdown-item">Profile</a>
                    {% endif %}
                    <a href="{{ url_for('logout.logout')}}" class="dropdown-item">Logout</a>
                    
                </div>
            </div>
        {% else %}
            <div>
                <i class="fa fa-user" aria-hidden="true"></i>
                <a href="{{ url_for('login.login')}}"><span>Login</span></a>
            </div>
        {% endif %}
    </div>
</header>

flask/website/templates/components/mobile-btn-large.html
{% macro newLargeButton(btn_link, btn_title, btn_icon, btn_alt) %}
<div class="row btn-larger-custom">
    <a href="{{ btn_link }}" id="find-localisation">
        <div class="col-11">
            <h3>{{ btn_title }}</h3>
        </div>
        <div class="col-1">
            <img src="{{ url_for('static', filename=btn_icon) }}" alt="{{ btn_alt }}">
        </div>
    </a>
</div>
{% endmacro %}

flask/website/templates/components/mobile-header.html
<div class="logo">
    <a href="{{ url_for('home.home') }}"><img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}"
            alt="logo BiKeeper">
        <h1>BiKeeper</h1>
    </a>
</div>
{% include "components/mobile-sidebar.html" %}
<nav onclick="openNav()">
    <img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu">
</nav>

flask/website/templates/components/mobile-sidebar-guest.html
<div id="myNav" class="overlay">

    <!-- Button to close the overlay navigation -->
    <img src="{{ url_for('static', filename='mobile/assets/close.png') }}" href="javascript:void(0)" class="closebtn" onclick="closeNav()" alt="close">

    <!-- Overlay content -->
      <div class="overlay-content">
          <div id="login">
              <img src="{{ url_for('static', filename='mobile/assets/login.png') }}" alt="login">
              <div class="centrer">
                  <a href="{{url_for('login.login') }}">Login</a>
              </div>

          </div>
          <div class="rectangle2"></div>
          <div id="register">
              <img src="{{ url_for('static', filename='mobile/assets/register.png') }}" alt="register">
              <div class="centrer"><a href="{{ url_for('register.register')}}">Register</a></div>
          </div>
          <div class="rectangle2"></div>
      </div>

  </div>

flask/website/templates/components/mobile-sidebar.html
<div id="myNav" class="overlay">

    <!-- Button to close the overlay navigation -->
    {% if not current_user.is_admin_user %}
    <a href="/faq/" id="help"><i class="fa fa-question"></i></a>
    {% endif %}
    <img src="{{ url_for('static', filename='mobile/assets/close.png') }}" href="javascript:void(0)" class="closebtn" onclick="closeNav()" alt="close">
    <!-- Overlay content -->
    <div class="container">
        <div id="img-profile"></div>
        <span>{{current_user.username_user}}</span>
        {% if not current_user.is_admin_user %}
        <a href="{{ url_for('home.home') }}">
        {% else %}
        <a href="{{ url_for('admin.admin_home') }}">
        {% endif %}
            <div class="row">
                <div class="col-2"><img src="{{ url_for('static', filename='mobile/assets/Vector.svg') }}" alt="vector"></div>
                <div class="col-10">Home</div>
            </div>
            <div class="rectangle2"></div>
        </a>
        {% if not current_user.is_admin_user %}
        <a href="{{ url_for('stats.statistics') }}">
            <div class="row">
                <div class="col-2"><img src="{{ url_for('static', filename='mobile/assets/graphicon1.svg') }}" alt="stat"></div>
                <div class="col-10">Statistics</div>
            </div>
            <div class="rectangle2"></div>
        </a>
        {% endif %}
        {% if current_user.is_admin_user %}
        <a href="{{ url_for('admin.admin_access') }}">
            <div class="row">
                <div class="col-2"><img src="{{ url_for('static', filename='mobile/assets/settings1.svg') }}" alt="setting"></div>
                <div class="col-10">Users</div>
            </div>
            <div class="rectangle2"></div>
        </a>
        {% endif %}
        {% if current_user.is_admin_user %}
        <a href="{{ url_for('admin.admin_access') }}">
            <div class="row">
                <div class="col-2"><img src="{{ url_for('static', filename='mobile/assets/layers.svg') }}" alt="setting"></div>
                <div class="col-10">Platform</div>
            </div>
            <div class="rectangle2"></div>
        </a>
        {% endif %}
        {% if not current_user.is_admin_user %}
        <a href="{{ url_for('settings.settings') }}">
            <div class="row">
                <div class="col-2"><img src="{{ url_for('static', filename='mobile/assets/settings1.svg') }}" alt="setting"></div>
                <div class="col-10">Settings</div>
            </div>
            <div class="rectangle2"></div>
        </a>
        {% endif %}
        <a href="{{ url_for('support.support') }}">
            <div class="row">
                <div class="col-2"><img src="{{ url_for('static', filename='mobile/assets/support.svg') }}" alt="support"></div>
                <div class="col-10">Support</div>
            </div>
            <div class="rectangle2"></div>
        </a>
        {% if not current_user.is_admin_user %}
        <a href="#" onclick="dropdown()">
            <div class="row">
                <div class="col-2"><img src="{{ url_for('static', filename='mobile/assets/Device.svg') }}" alt="device"></div>
                <div class="col-10">Device</div>
            </div>
            <div class="rectangle2"></div>
        </a>
        <div class="drpdwn">
            <div id="dropdown">
                <div class="row" id="devices">
                {% for device in devices %}
                <form action="{{ url_for('sidebar.sidebar_device_change') }}" method="POST">
                    <button type='submit' name="device_change" value="{{device.num_device}}" class="dropdown-item">{{ device.name_device }}</button>
                </form>
                {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        <a href="{{ url_for('logout.logout')}}">
            <div class="row">
                <div class="col-2"><img src="{{ url_for('static', filename='mobile/assets/log_out.svg') }}" alt="log_out" id="Disconnect"></div>
                <div class="col-10">Disconnect</div>
            </div>
            <div class="rectangle2"></div>
        </a>
    </div>
</div>
<script type="text/javascript">
    function dropdown() {
        console.log(document.getElementById("dropdown").style.display)
        if (document.getElementById("dropdown").style.display.localeCompare("") ==0 || document.getElementById("dropdown").style.display.localeCompare("none")==0 ){
            document.getElementById("dropdown").style.display="block";
            console.log("oui")
        }
        else{
            document.getElementById("dropdown").style.display="none";
            console.log("non")
        }
        

    }
    function post(username,id_device) {
        let url = "/api/test/update_device/"+ username + "/" + id_device + "/";
        console.log(url);
        return new Promise((resolve, reject) => {
            const req = new XMLHttpRequest();
            req.open('POST', url);
            req.onload = () => req.status === 200 ? resolve(req.response) : reject(Error(req.statusText));
            req.onerror = (e) => reject(Error(`Network Error: ${e}`));
            req.send();
        });
}
</script>

flask/website/templates/components/sidebar.html
<aside class="sidebar sidebar-navigation">
    {% if not current_user.is_admin_user %}
    <a href="/faq/" id="help">Besoin d'aide ?</a>
    {% endif %}
    <ul>
        {% if not current_user.is_admin_user %}
        <li>
            <div>
                <img src="{{ url_for('static', filename='pc/assets/home-icon.svg') }}" alt="icone home">
                <a href="{{ url_for('home.home') }}">
                    Accueil
                </a>
            </div>
        </li>
        <li>
            <div>
                <img src="{{ url_for('static', filename='pc/assets/statistics.png') }}" alt="icone statistics">               
                <a href="{{ url_for('stats.statistics') }}">
                    Statistics
                </a>
            </div>
        </li>
        <li>
            <div>
                <img src="{{ url_for('static', filename='pc/assets/settings.png') }}" alt="icone settings">                
                <a href="{{ url_for('settings.settings') }}">
                    Settings
                </a>
            </div>
        </li>
        {% else %}
        <li>
            <div>
                <img src="{{ url_for('static', filename='pc/assets/home-icon.svg') }}" alt="icone home">
                <a href="{{ url_for('admin.admin_home') }}">
                    Accueil
                </a>
            </div>
        </li>
        <li>
            <div>
                <img src="{{ url_for('static', filename='pc/assets/users-icon.svg') }}" alt="icone statistics">               
                <a href="{{ url_for('stats.statistics') }}">
                    Users
                </a>
            </div>
        </li>
        <li>
            <div>
                <img src="{{ url_for('static', filename='pc/assets/plateform-icon.svg') }}" alt="icone settings">                
                <a href="{{ url_for('admin.platform') }}">
                    Plateform
                </a>
            </div>
        </li>
        {% endif %}
        <li>
            <div>
                <img src="{{ url_for('static', filename='pc/assets/support.png') }}" alt="icone support">
                <a href="{{ url_for('support.support') }}">
                    Support
                </a>
            </div>
        </li>
        {% if not current_user.is_admin_user %}
        <li>
            <div class="dropdown show">
                <img src="{{ url_for('static', filename='pc/assets/device.svg') }}" alt="icone device">
                <a class='dropdown-toggle"' href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Devices
                </a>
              
                <div class="dropdown-menu" id="devices" aria-labelledby="dropdownMenuLink">
                    {% for device in devices %}
                        <form action="{{ url_for('sidebar.sidebar_device_change') }}" method="POST">
                            <button type='submit' name="device_change" value="{{device.num_device}}" class="dropdown-item">{{ device.name_device }}</button>
                        </form>
                    {% endfor %}
                </div>
            </div>
        </li>
        {% endif %}
    </ul>
</aside>